export { default as Navbar } from "./navbar/Navbar";
export { default as Header } from "./header/Header";
export { default as Footer } from "./footer/Footer";
export { default as Section1 } from "./section1/section1";
export { default as Section2 } from "./section2/Section2";
export { default as Section3 } from "./section3/Section3";
export { default as Section4 } from "./section4/Section4";
export { default as Section5 } from "./section5/Section5";
export { default as Section6 } from "./section6/Section6";
